CREATE TABLE Auto (
	id INTEGER PRIMARY KEY NOT NULL, 
	rekkari VARCHAR(140) NOT NULL, 
	merkki VARCHAR(140) NOT NULL, 
	malli VARCHAR(140) NOT NULL
	);

CREATE TABLE Kuljettaja (
	id INTEGER PRIMARY KEY NOT NULL, 
	etunimi VARCHAR(140) NOT NULL, 
	sukunimi VARCHAR(140) NOT NULL
	);

CREATE TABLE Ajovuoro (
	id INTEGER PRIMARY KEY NOT NULL, 
	kuljettaja_id INTEGER NOT NULL,
	auto_id INTEGER NOT NULL,
	km DECIMAL(10,2) NOT NULL, 
	aika DECIMAL(10,2) NOT NULL, 
	FOREIGN KEY (kuljettaja_id) REFERENCES kuljettaja(id), 
	FOREIGN KEY(auto_id) REFERENCES auto(id)
	);

CREATE TABLE Kyyti (
	id INTEGER PRIMARY KEY NOT NULL, 
	ajovuoro_id INTEGER NOT NULL, 
	hinta DECIMAL(10,2),
	km DECIMAL(10,2) NOT NULL, 
	aika DECIMAL(10,2) NOT NULL, 	 
	FOREIGN KEY(ajovuoro_id) REFERENCES ajovuoro(id)
	);

