CREATE TABLE Auto (
	id SERIAL PRIMARY KEY,
	rekkari VARCHAR(22) NOT NULL,
	asemapaikka VARCHAR(22) NOT NULL, 
	merkki VARCHAR(22) NOT NULL, 
	malli VARCHAR(22) NOT NULL
	);
CREATE TABLE Kuljettaja (
	id SERIAL PRIMARY KEY, 
	etunimi VARCHAR(22) NOT NULL, 
	sukunimi VARCHAR(22) NOT NULL
	);
CREATE TABLE Ajovuoro (
	id SERIAL PRIMARY KEY,
	kuljettaja_id INTEGER NOT NULL,
	auto_id INTEGER NOT NULL,
	km DECIMAL(10,2) NOT NULL, 
	aika DECIMAL(10,2) NOT NULL, 
	FOREIGN KEY (kuljettaja_id) REFERENCES kuljettaja(id) ON DELETE CASCADE ON UPDATE CASCADE, 
	FOREIGN KEY (auto_id) REFERENCES auto(id) ON DELETE CASCADE ON UPDATE CASCADE
	);
CREATE TABLE Kyyti (
	id SERIAL PRIMARY KEY, 
	ajovuoro_id INTEGER NOT NULL, 
	hinta DECIMAL(10,2) NOT NULL,
	km DECIMAL(10,2) NOT NULL, 
	aika DECIMAL(10,2) NOT NULL, 	 
	FOREIGN KEY(ajovuoro_id) REFERENCES ajovuoro(id) ON DELETE CASCADE ON UPDATE CASCADE
	);
CREATE TABLE Kayttaja (
	id SERIAL PRIMARY KEY,
	tunnus VARCHAR(8) NOT NULL,
	salasana VARCHAR(8) NOT NULL
	);
